### ISSUE TITLE
collectd doesn't start

### ISSUE THREAD

**Issue by carmenfdezb** [rinigus/systemdatascope#22] opened 2016-07-17 17:47 UTC
Collect stopped since I installed last version (SystamDataScope 0.2.3-1, collectd 5.5.0) because /tmp/collectd/Jolla doesn't exist. Is this a bug or are there any way yo solve this issue?
Thanks for your attention.

**Comment by rinigus** [comment] 2016-07-17 18:23
Hi! Let's see what's going on. When collectd is stopped, that directory should not exist. Its created while starting and moved away on stop.

In SystemDataScope: try to go to settings and start collectd by pressing Run collectd. After that, go to Status and check if all is OK. If the bug is still there, please copy text in Status and paste it here (use pulley menu in Status for copy).

Let me know how it went

**Comment by rinigus** [comment] 2016-07-17 18:25
One question: how did you try to start collectd?

**Comment by carmenfdezb** [comment] 2016-07-17 18:31
I did that you say:

<b>collectd:</b> Stopped / Will not start on boot

<b>RRDtool:</b> Running

<b>Last state of the loading URL:</b> 

<b>Last RRDtool error:</b> 

<b>Use SystemDataScope to enable/disable collectd:</b> true

<b>Folder with the collectd databases while running:</b> /tmp/collectd/Jolla : check result : Error: Directory does not exists

<b>Folder with the collectd databases while the daemon is stopped:</b> /home/nemo/.local/share/collectd/Jolla : check result : OK

<b>Loaded configuration:</b>

<small><b>Page: Overview</b>

  CPU/overview
    <b>Page: CPU details</b>
      CPU/overview
      CPU/idle
      CPU/nice
      CPU/user
      CPU/system
      CPU/wait
      CPU/steal
      CPU/softirq
      CPU/interrupt

  Battery/voltage
    <b>Page: Battery details</b>
      Battery/voltage
      Battery/percent-discharged
      Battery/percent-charged
      Battery/current

  Storage/root
    <b>Page: Storage details</b>
      Storage/tmp
      Storage/root
      Disk/mmcblk1/ops
      Disk/mmcblk1/octets
      Disk/mmcblk1/merged
      Disk/mmcblk1/io_time
      Disk/mmcblk0/ops
      Disk/mmcblk0/octets
      Disk/mmcblk0/merged
      Disk/mmcblk0/io_time

  Memory/overview
    <b>Page: Memory details</b>
      Memory/overview
      Memory/free
      Memory/cached
      Memory/buffered
      Memory/used
      Memory/slab_recl
      Memory/slab_unrecl

  Network/wlan0/octets
    <b>Page: Network details</b>

```
  Network/wlan0/octets
    <b>Page: Network details: wlan0</b>
      Network/wlan0/packets
      Network/wlan0/octets
      Network/wlan0/errors
      Network/wlan0/dropped


  Network/sit0/octets
    <b>Page: Network details: sit0</b>
      Network/sit0/packets
      Network/sit0/octets
      Network/sit0/errors
      Network/sit0/dropped


  Network/rmnet7/octets
    <b>Page: Network details: rmnet7</b>
      Network/rmnet7/packets
      Network/rmnet7/octets
      Network/rmnet7/errors
      Network/rmnet7/dropped


  Network/rmnet6/octets
    <b>Page: Network details: rmnet6</b>
      Network/rmnet6/packets
      Network/rmnet6/octets
      Network/rmnet6/errors
      Network/rmnet6/dropped


  Network/rmnet5/octets
    <b>Page: Network details: rmnet5</b>
      Network/rmnet5/packets
      Network/rmnet5/octets
      Network/rmnet5/errors
      Network/rmnet5/dropped


  Network/rmnet4/octets
    <b>Page: Network details: rmnet4</b>
      Network/rmnet4/packets
      Network/rmnet4/octets
      Network/rmnet4/errors
      Network/rmnet4/dropped


  Network/rmnet3/octets
    <b>Page: Network details: rmnet3</b>
      Network/rmnet3/packets
      Network/rmnet3/octets
      Network/rmnet3/errors
      Network/rmnet3/dropped


  Network/rmnet2/octets
    <b>Page: Network details: rmnet2</b>
      Network/rmnet2/packets
      Network/rmnet2/octets
      Network/rmnet2/errors
      Network/rmnet2/dropped


  Network/rmnet1/octets
    <b>Page: Network details: rmnet1</b>
      Network/rmnet1/packets
      Network/rmnet1/octets
      Network/rmnet1/errors
      Network/rmnet1/dropped


  Network/rmnet0/octets
    <b>Page: Network details: rmnet0</b>
      Network/rmnet0/packets
      Network/rmnet0/octets
      Network/rmnet0/errors
      Network/rmnet0/dropped


  Network/p2p0/octets
    <b>Page: Network details: p2p0</b>
      Network/p2p0/packets
      Network/p2p0/octets
      Network/p2p0/errors
      Network/p2p0/dropped


  Network/lo/octets
    <b>Page: Network details: lo</b>
      Network/lo/packets
      Network/lo/octets
      Network/lo/errors
      Network/lo/dropped
```

  Load/load
    <b>Page: Load details</b>
      Load/load
      Context/context_switch
      Entropy/entropy

  Processes/overview
    <b>Page: Processes details</b>
      Processes/overview
      Processes/fork_rate
      Processes/sleeping
      Processes/stopped
      Processes/running
      Processes/blocked
      Processes/paging
      Processes/zombies

  Uptime/uptime

N/A corresponds to the non-available plot (RRD file is missing, for example)
</small>

**Comment by carmenfdezb** [comment] 2016-07-17 18:33
I tried to start collectd from settings (I actived 'Run collectd' and 'Accept', but it doesn't work)

**Comment by rinigus** [comment] 2016-07-17 18:43
Thank you for fast reply and status. This sounds as a bug, so let's try to fix it.

In my phone, when I press "Run", I don't have to press Accept since run should lead to reloading of configuration. Try to press Run and wait a bit. If that doesn't work, then let's move to terminal.

In terminal, as a user nemo (NOT ROOT), run:

systemctl --user status collectd.service

If collectd.service is inactive (like "Active: inactive (dead)"), try to start it:

systemctl --user start collectd.service

Do you see any error messages? Check after start, the status using systemctl status command above.

**Comment by carmenfdezb** [comment] 2016-07-17 19:15
I see error messages in Terminal:
![screenshot-16-07-17-21-09-44](https://cloud.githubusercontent.com/assets/6286776/16902580/938ce594-4c63-11e6-8b42-bb509583da44.png)

**Comment by rinigus** [comment] 2016-07-17 19:52
OK, from this it is clear that collectd itself does not start. Now, we can do all this systemd magic manually and see where it fails. 

In terminal:
1. to make the folder /tmp/collectd, run:

collectd2tmpfs --init
1. start collectd manually:

collectd -f

I expect that it fails somewhere. If it doesn't you can stop it with Ctrl-C. As for folder /tmp/collectd, you could then just remove it with your old recordings staying in your home.

Let me know how it went. Its getting bit late over here, so I may reply to the next message only tomorrow.

**Comment by carmenfdezb** [comment] 2016-07-17 20:20
Thank you for your attention again ;)
I did that you say,  here it is a screenshot:
![screenshot-16-07-17-22-13-09](https://cloud.githubusercontent.com/assets/6286776/16902856/783d23e0-4c6c-11e6-94d8-f4b47b2b7a72.png)
It seems that there is an error with battery plugin.

**Comment by rinigus** [comment] 2016-07-17 20:28
OK, let me fix it. There is also missing cpusleep plugin (somehow I managed to configure without it). Let me fix these errors and upload a new RPMs in OpenRepos for collectd.

As for failure to start, there is something else. Do you have 2 configuration files (one with rpmsave in the end?). Or maybe you could send me 

/etc/collectd.conf

**Comment by carmenfdezb** [comment] 2016-07-17 20:44
Ok, thank you very much!!

I don't have .rpmsave file, only collectd.conf:

https://db.tt/iw9fxlEq

**Comment by rinigus** [comment] 2016-07-17 20:55
The new RPM for collectd is out at OpenRepos. Upgrade and try again. Maybe you could start from GUI - let's see if it works. I'll take a look into your config file in a moment.

**Comment by rinigus** [comment] 2016-07-17 21:05
Your config seems to be absolutely fine (except battery). So, my hope is that the missing cpusleep triggered this failure.

**Comment by carmenfdezb** [comment] 2016-07-17 21:09
Great!! Now it works!!!!
Thank you so much, it's a really useful app

**Comment by rinigus** [comment] 2016-07-17 21:10
... and I managed to reproduce your failure by removing cpusleep.so. 

So, I really hope that you managed to get it running with the new version.

**Comment by rinigus** [comment] 2016-07-17 21:17
Excellent news! Thank you very much for sticking with it and reporting back!

One tip regarding your config: there are lots of network interfaces that were reported before. Now, in the new version, only active interfaces are reported. So, you could avoid all this mess by:
1. stop collectd
2. go to .local/share/collectd/Jolla and delete all subfolders with interface-XXXXX that's not used (was always zero in reports).
3. start collectd
4. for efficiency, in SystemDataScope, go to settings and regenerate configuration.

The bug was induced by a strange rpm behavior on upgrade - its not deleting a file if it was in the old version, but is absent in the new one.

**Comment by rinigus** [comment] 2016-07-17 21:18
.., I'll keep this bugreport around, there are few things that I should fix in future regarding user interaction and it will help me to do so.

**Comment by carmenfdezb** [comment] 2016-07-17 21:41
Ok, thank you!!!

**Comment by rinigus** [comment] 2016-07-23 17:16
The confusing messages are fixed in the latest commits. Among them: 
- message regarding missing directories is now more precise and tells whether the directory is actually expected or not
- starting and enabling collectd is applied only after the settings dialog is closed with accept.

The changes will be released in the next version together with new support for new collectd plugins.

Thank you for your help! Please report back if something is wrong.

I am closing this issue, please open new ones if needed

**Closed as completed by rinigus** 2016-07-23 17:16 UTC
